/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import conf.MyFonction;
import conf.Utils;
import java.awt.Cursor;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.User;
import utils.UtilsFonction;

import javax.swing.JOptionPane;

/**
 *
 * @author couly
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
      
        initComponents();
        setLocationRelativeTo(null);
        Utils.init();
        if(loadUser()){
            role_cbx.setVisible(false);
        }else{
            role_cbx.setVisible(true);
        }
        signin_panel.setVisible(false);

    }
    public boolean loadUser() {
    try {
        List<User> userList = Utils.getiUser().allUser();
        
        for(User user : userList){
            if(user.getRole().equals("ADMIN")){
                return true;
            } 
        }
    } catch (RemoteException ex) {
        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
    }
    return false;
}







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        connexion_btn = new javax.swing.JLabel();
        sign_in_btn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        signin_panel = new javax.swing.JPanel();
        login_panel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwords_txt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logins_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        confirm_passwords_txt = new javax.swing.JPasswordField();
        role_cbx = new javax.swing.JComboBox<>();
        inscription_btn = new javax.swing.JLabel();
        retour_btn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        login_panel.setBackground(new java.awt.Color(204, 204, 204));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\couly\\Downloads\\casual-life-3d-yellow-padlock-with-key.png")); // NOI18N
        login_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 318, 508));

        login_txt.setBackground(new java.awt.Color(102, 102, 102));
        login_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_txt.setForeground(new java.awt.Color(0, 0, 0));
        login_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login_panel.add(login_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 200, 251, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOGIN");
        login_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 168, -1, -1));

        password_txt.setBackground(new java.awt.Color(102, 102, 102));
        password_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        password_txt.setForeground(new java.awt.Color(0, 0, 0));
        password_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login_panel.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 285, 251, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PASSWORD");
        login_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 259, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("LOGIN");
        login_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 97, 97, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        login_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 0, -1, 520));

        connexion_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Checkmark_40px.png"))); // NOI18N
        connexion_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connexion_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                connexion_btnMouseEntered(evt);
            }
        });
        login_panel.add(connexion_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 50, 60));

        sign_in_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Plus_48px_1.png"))); // NOI18N
        sign_in_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_in_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_in_btnMouseEntered(evt);
            }
        });
        login_panel.add(sign_in_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 6, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pexels-codioful-(formerly-gradienta)-7135069.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        login_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        signin_panel.setBackground(new java.awt.Color(204, 204, 204));

        login_panel1.setBackground(new java.awt.Color(204, 204, 204));
        login_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\couly\\Downloads\\casual-life-3d-yellow-padlock-with-key.png")); // NOI18N
        login_panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 318, 496));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("LOGIN");
        login_panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 90, -1, -1));

        passwords_txt.setBackground(new java.awt.Color(153, 153, 153));
        passwords_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwords_txt.setForeground(new java.awt.Color(0, 0, 0));
        passwords_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login_panel1.add(passwords_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 254, 220, 41));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PASSWORD");
        login_panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 228, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("SIGN IN");
        jLabel8.setToolTipText("");
        login_panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 53, 97, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        login_panel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 0, -1, 508));

        logins_txt.setBackground(new java.awt.Color(153, 153, 153));
        logins_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logins_txt.setForeground(new java.awt.Color(0, 0, 0));
        logins_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login_panel1.add(logins_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 116, 219, 33));

        email_txt.setBackground(new java.awt.Color(153, 153, 153));
        email_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 0, 0));
        email_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login_panel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 181, 219, 41));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("EMAIL");
        login_panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 155, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CONFIRM PASSWORD");
        login_panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 301, -1, -1));

        confirm_passwords_txt.setBackground(new java.awt.Color(153, 153, 153));
        confirm_passwords_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirm_passwords_txt.setForeground(new java.awt.Color(0, 0, 0));
        confirm_passwords_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        login_panel1.add(confirm_passwords_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 327, 220, 35));

        role_cbx.setBackground(new java.awt.Color(204, 204, 204));
        role_cbx.setForeground(new java.awt.Color(0, 0, 0));
        role_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMPLOYE", "ADMIN", " " }));
        role_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_cbxActionPerformed(evt);
            }
        });
        login_panel1.add(role_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 374, 137, 28));

        inscription_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Checkmark_40px.png"))); // NOI18N
        inscription_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscription_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inscription_btnMouseEntered(evt);
            }
        });
        login_panel1.add(inscription_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 428, -1, 54));

        retour_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Share_48px.png"))); // NOI18N
        retour_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retour_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retour_btnMouseEntered(evt);
            }
        });
        login_panel1.add(retour_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 0, 59, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/degraded-g4a4817857_1280.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        login_panel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        javax.swing.GroupLayout signin_panelLayout = new javax.swing.GroupLayout(signin_panel);
        signin_panel.setLayout(signin_panelLayout);
        signin_panelLayout.setHorizontalGroup(
            signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signin_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(login_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        signin_panelLayout.setVerticalGroup(
            signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signin_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(login_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscription_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscription_btnMouseClicked
        // TODO add your handling code here:
        try {

            String email = email_txt.getText();
            String logins = logins_txt.getText();
            String passwords = UtilsFonction.encrypt(new String(passwords_txt.getPassword()));
            String passwordsConfirme = new String(passwords_txt.getPassword());
            String passwordsConfirme1 = new String(confirm_passwords_txt.getPassword());
            String role = role_cbx.getSelectedItem().toString();


            if (!MyFonction.confirmPassword(passwordsConfirme, passwordsConfirme1)) {
                JOptionPane.showMessageDialog(null, "Les mots de passe ne sont pas identiques");
                return;
            }
            

            if (MyFonction.validerEmail(email)) {
                JOptionPane.showMessageDialog(null, "Veuillez entrer un email valide");
                return;
            }

            if (!MyFonction.validatePassword(passwordsConfirme)) {

                JOptionPane.showMessageDialog(null, "Veuillez entrer un mots de passe valide");
                return;
            }
            
            User userT = Utils.getiUser().getConnexion(logins);
             if(userT != null){
                 JOptionPane.showMessageDialog(null, "Ce login existe deja");
                return;
             
             }
             
              User userM = Utils.getiUser().getUserMail(email);
             if(userM != null){
                 JOptionPane.showMessageDialog(null, "Ce mail existe deja");
                return;
             
             }

            User user = new User(logins, passwords, email, role, "BLOQUER");
            User add = Utils.getiUser().addUser(user);
            if (add.getId() != null) {
                MyFonction.clearSignin(email_txt, logins_txt, passwords_txt, confirm_passwords_txt);
                JOptionPane.showMessageDialog(null, "votre compte a ete cree avec succes");
                signin_panel.setVisible(false);
                login_panel.setVisible(true);
            }
        } catch (RemoteException ex) {
            System.err.println("Erreur : " + ex.getMessage());
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_inscription_btnMouseClicked

    private void retour_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour_btnMouseClicked
        // TODO add your handling code here:
        login_panel.setVisible(true);
        signin_panel.setVisible(false);
    }//GEN-LAST:event_retour_btnMouseClicked

    private void sign_in_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_btnMouseClicked
        // TODO add your handling code here:
        login_panel.setVisible(false);
        signin_panel.setVisible(true);
    }//GEN-LAST:event_sign_in_btnMouseClicked

    private void connexion_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexion_btnMouseEntered
        // TODO add your handling code here:
        connexion_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_connexion_btnMouseEntered

    private void sign_in_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_btnMouseEntered
        // TODO add your handling code here:
        sign_in_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sign_in_btnMouseEntered

    private void inscription_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscription_btnMouseEntered
        // TODO add your handling code here:
        inscription_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inscription_btnMouseEntered

    private void retour_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour_btnMouseEntered
        // TODO add your handling code here:
        retour_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_retour_btnMouseEntered

    private void connexion_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexion_btnMouseClicked
        // TODO add your handling code here:
        try {
            String login = login_txt.getText();
            String password = password_txt.getText();
            User user = Utils.getiUser().getConnexion(login);
            if (user != null) {
                String decryptPassowrd = UtilsFonction.decrypt(user.getPassword());
                if (decryptPassowrd.equals(password)) {
                    if (user.getEtat().equalsIgnoreCase("ACTIVER")) {
                        new chargement(user).setVisible(true);
                        this.dispose();
                    } else {
                            JOptionPane.showMessageDialog(null, "Votre n'est pas autoriser contacter l'administrateur");
                            return;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Login ou password incorrect");
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login ou passworddd incorrect");
                return;
            }
        } catch (RemoteException ex) {
            System.err.println("Erreur : " + ex.getMessage());
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_connexion_btnMouseClicked

    private void role_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role_cbxActionPerformed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_passwords_txt;
    private javax.swing.JLabel connexion_btn;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel inscription_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login_panel;
    private javax.swing.JPanel login_panel1;
    private javax.swing.JTextField login_txt;
    private javax.swing.JTextField logins_txt;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JPasswordField passwords_txt;
    private javax.swing.JLabel retour_btn;
    private javax.swing.JComboBox<String> role_cbx;
    private javax.swing.JLabel sign_in_btn;
    private javax.swing.JPanel signin_panel;
    // End of variables declaration//GEN-END:variables
}
