/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import conf.MyFonction;
import conf.Utils;
import java.awt.Cursor;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.User;
import utils.UtilsFonction;

import javax.swing.JOptionPane;

/**
 *
 * @author couly
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        startServer();
        initComponents();
        setLocationRelativeTo(null);
        Utils.init();
        if(loadUser()){
            role_cbx.setVisible(false);
        }else{
            role_cbx.setVisible(true);
        }
        signin_panel.setVisible(false);

    }
    public boolean loadUser() {
    try {
        List<User> userList = Utils.getiUser().allUser();
        
        for(User user : userList){
            if(user.getRole().equals("ADMIN")){
                return true;
            } 
        }
    } catch (RemoteException ex) {
        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
    }
    return false;
}
 private static void startServer() {
    try {
        String serverJarPath = "C:\\Users\\couly\\OneDrive\\Documents\\NetBeansProjects\\AppMuseeServer\\dist\\AppMuseeServer.jar";
        Process process = Runtime.getRuntime().exec("java -jar " + serverJarPath);
        System.out.println("Serveur démarré avec succès.");
    } catch (IOException e) {
        e.printStackTrace();
        System.err.println("Erreur lors du démarrage du serveur.");
    }
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        connexion_btn = new javax.swing.JLabel();
        sign_in_btn = new javax.swing.JLabel();
        signin_panel = new javax.swing.JPanel();
        login_panel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwords_txt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logins_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        confirm_passwords_txt = new javax.swing.JPasswordField();
        role_cbx = new javax.swing.JComboBox<>();
        inscription_btn = new javax.swing.JLabel();
        retour_btn = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        login_panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\couly\\Downloads\\casual-life-3d-yellow-padlock-with-key.png")); // NOI18N

        login_txt.setBackground(new java.awt.Color(102, 102, 102));
        login_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_txt.setForeground(new java.awt.Color(0, 0, 0));
        login_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOGIN");

        password_txt.setBackground(new java.awt.Color(102, 102, 102));
        password_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        password_txt.setForeground(new java.awt.Color(0, 0, 0));
        password_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PASSWORD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("LOGIN");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        connexion_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Checkmark_40px.png"))); // NOI18N
        connexion_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connexion_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                connexion_btnMouseEntered(evt);
            }
        });

        sign_in_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Plus_48px_1.png"))); // NOI18N
        sign_in_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_in_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_in_btnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel2))
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(connexion_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(153, 153, 153))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                                .addComponent(sign_in_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addComponent(sign_in_btn)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(login_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(connexion_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        signin_panel.setBackground(new java.awt.Color(204, 204, 204));

        login_panel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\couly\\Downloads\\casual-life-3d-yellow-padlock-with-key.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("LOGIN");

        passwords_txt.setBackground(new java.awt.Color(153, 153, 153));
        passwords_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwords_txt.setForeground(new java.awt.Color(0, 0, 0));
        passwords_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PASSWORD");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("SIGN IN");
        jLabel8.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        logins_txt.setBackground(new java.awt.Color(153, 153, 153));
        logins_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logins_txt.setForeground(new java.awt.Color(0, 0, 0));
        logins_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        email_txt.setBackground(new java.awt.Color(153, 153, 153));
        email_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 0, 0));
        email_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("EMAIL");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CONFIRM PASSWORD");

        confirm_passwords_txt.setBackground(new java.awt.Color(153, 153, 153));
        confirm_passwords_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirm_passwords_txt.setForeground(new java.awt.Color(0, 0, 0));
        confirm_passwords_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        role_cbx.setBackground(new java.awt.Color(204, 204, 204));
        role_cbx.setForeground(new java.awt.Color(0, 0, 0));
        role_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "EMPLOYE" }));
        role_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_cbxActionPerformed(evt);
            }
        });

        inscription_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Checkmark_40px.png"))); // NOI18N
        inscription_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscription_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inscription_btnMouseEntered(evt);
            }
        });

        retour_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/i/icons8_Share_48px.png"))); // NOI18N
        retour_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retour_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retour_btnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout login_panel1Layout = new javax.swing.GroupLayout(login_panel1);
        login_panel1.setLayout(login_panel1Layout);
        login_panel1Layout.setHorizontalGroup(
            login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(inscription_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                    .addGroup(login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(logins_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(passwords_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(66, 66, 66))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                    .addGroup(login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(login_panel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel6))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(125, 125, 125))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(169, 169, 169))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(145, 145, 145))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(97, 97, 97))
                                .addGroup(login_panel1Layout.createSequentialGroup()
                                    .addComponent(confirm_passwords_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                .addComponent(role_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panel1Layout.createSequentialGroup()
                                .addComponent(retour_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        login_panel1Layout.setVerticalGroup(
            login_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(login_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(login_panel1Layout.createSequentialGroup()
                .addComponent(retour_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logins_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwords_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirm_passwords_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(role_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(inscription_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout signin_panelLayout = new javax.swing.GroupLayout(signin_panel);
        signin_panel.setLayout(signin_panelLayout);
        signin_panelLayout.setHorizontalGroup(
            signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signin_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(login_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        signin_panelLayout.setVerticalGroup(
            signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(signin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signin_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(login_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscription_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscription_btnMouseClicked
        // TODO add your handling code here:
        try {

            String email = email_txt.getText();
            String logins = logins_txt.getText();
            String passwords = UtilsFonction.encrypt(new String(passwords_txt.getPassword()));
            String passwordsConfirme = new String(passwords_txt.getPassword());
            String passwordsConfirme1 = new String(confirm_passwords_txt.getPassword());
            String role = role_cbx.getSelectedItem().toString();


            if (!MyFonction.confirmPassword(passwordsConfirme, passwordsConfirme1)) {
                JOptionPane.showMessageDialog(null, "Les mots de passe ne sont pas identiques");
                return;
            }
            

            if (MyFonction.validerEmail(email)) {
                JOptionPane.showMessageDialog(null, "Veuillez entrer un email valide");
                return;
            }

            if (!MyFonction.validatePassword(passwordsConfirme)) {

                JOptionPane.showMessageDialog(null, "Veuillez entrer un mots de passe valide");
                return;
            }
            
            User userT = Utils.getiUser().getConnexion(logins);
             if(userT != null){
                 JOptionPane.showMessageDialog(null, "Ce login existe deja");
                return;
             
             }
             
              User userM = Utils.getiUser().getUserMail(email);
             if(userM != null){
                 JOptionPane.showMessageDialog(null, "Ce mail existe deja");
                return;
             
             }

            User user = new User(logins, passwords, email, role, "active");
            User add = Utils.getiUser().addUser(user);
            if (add.getId() != null) {
                MyFonction.clearSignin(email_txt, logins_txt, passwords_txt, confirm_passwords_txt);
                JOptionPane.showMessageDialog(null, "votre compte a ete cree avec succes");
                signin_panel.setVisible(false);
                login_panel.setVisible(true);
            }
        } catch (RemoteException ex) {
            System.err.println("Erreur : " + ex.getMessage());
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_inscription_btnMouseClicked

    private void retour_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour_btnMouseClicked
        // TODO add your handling code here:
        login_panel.setVisible(true);
        signin_panel.setVisible(false);
    }//GEN-LAST:event_retour_btnMouseClicked

    private void sign_in_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_btnMouseClicked
        // TODO add your handling code here:
        login_panel.setVisible(false);
        signin_panel.setVisible(true);
    }//GEN-LAST:event_sign_in_btnMouseClicked

    private void connexion_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexion_btnMouseEntered
        // TODO add your handling code here:
        connexion_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_connexion_btnMouseEntered

    private void sign_in_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_btnMouseEntered
        // TODO add your handling code here:
        sign_in_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sign_in_btnMouseEntered

    private void inscription_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscription_btnMouseEntered
        // TODO add your handling code here:
        inscription_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inscription_btnMouseEntered

    private void retour_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retour_btnMouseEntered
        // TODO add your handling code here:
        retour_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_retour_btnMouseEntered

    private void connexion_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexion_btnMouseClicked
        // TODO add your handling code here:
        try {
            String login = login_txt.getText();
            String password = password_txt.getText();
            User user = Utils.getiUser().getConnexion(login);
            if (user != null) {
                String decryptPassowrd = UtilsFonction.decrypt(user.getPassword());
                if (decryptPassowrd.equals(password)) {

                    new App(user).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login ou password incorrect");

                }
            } else {
                JOptionPane.showMessageDialog(null, "Login ou passworddd incorrect");

            }
        } catch (RemoteException ex) {
            System.err.println("Erreur : " + ex.getMessage());
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_connexion_btnMouseClicked

    private void role_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role_cbxActionPerformed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_passwords_txt;
    private javax.swing.JLabel connexion_btn;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel inscription_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login_panel;
    private javax.swing.JPanel login_panel1;
    private javax.swing.JTextField login_txt;
    private javax.swing.JTextField logins_txt;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JPasswordField passwords_txt;
    private javax.swing.JLabel retour_btn;
    private javax.swing.JComboBox<String> role_cbx;
    private javax.swing.JLabel sign_in_btn;
    private javax.swing.JPanel signin_panel;
    // End of variables declaration//GEN-END:variables
}
